export const breakdownTest = {
  code: 200,
  result: [
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 1,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 2,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 3,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 4,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 5,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 6,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 7,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 8,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 9,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 10,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 11,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 12,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 13,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 14,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 15,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 16,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 17,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 18,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 19,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 20,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 21,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 22,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 23,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 24,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 25,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 26,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 27,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 28,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 29,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 30,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 31,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 32,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 33,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 34,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 35,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 36,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 37,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 38,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 39,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 40,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 41,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 42,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 43,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 44,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 45,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 46,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 47,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 48,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 49,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 50,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 51,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 52,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 53,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 54,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 55,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 56,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 57,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 58,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 59,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 60,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 61,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 62,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 63,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 64,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 65,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 66,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 67,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 68,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 69,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 70,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 71,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 72,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 73,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 74,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 75,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 76,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 77,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 78,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 79,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 80,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 81,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 82,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 83,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 84,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 85,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 86,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 87,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 88,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 89,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 90,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 91,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 92,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 93,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 94,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 95,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 96,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 97,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 98,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 99,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
    {
      allAwbReceive: false,
      awbTotalPiece: 100,
      barcode: '010101',
      depth: 0.22,
      description: '배송설명',
      destination: 'SIN',
      gSkidOn: false,
      ghost: true,
      id: 26500,
      length: 0.22,
      modelPath: null,
      parent: 24748,
      path: null,
      piece: 1,
      prefab: '3d Model Name',
      receivedDate: '20231122120754',
      receivedUser: 'VN762',
      scc: ['GEN', 'EAT'],
      separateNumber: 100,
      simulation: true,
      spawnRatio: 1,
      squareVolume: 1,
      state: 'saved',
      waterVolume: 1,
      weight: 5.0,
      width: 0.22,
    },
  ],
  state: 'Success',
};
